### ISSUE TITLE
Documentation Background Color Changes

### ISSUE THREAD

**Issue by Miserlou** [amark/gun#784]
This is nauseating. Why would anybody want this. Please just choose a color.

**Comment by amark** [comment]
@miserlou you can always read the docs from the boring source github wiki pages: http://github.com/amark/gun/wiki

**Comment by rumkin** [comment]
@amark Well, the wiki is gone and has been moved to the website. As you can see I've spent my time  to dig into this issue too. Colorchanging background isn't user-friendly, especially to people with color blindness or other color issues. I'd suggest to have a settings button to switch contrast color schemes and to let users control this.

What's for me it's just annoying because it distracts me from the reading. I need to spent some time to unsee the color change and it's really hard, especially when it become red. If you don't want to change this, then I suggest to add a switcher. I would appreciate this a lot.

**Comment by Dletta** [comment]
@rumkin The wiki pages are the source of the website. If you find a doc you want to read, search in the wiki search page and you will find it with a nice white / black background (depending on dark mode)

**Comment by rumkin** [comment]
@dletta It doesn't seem to be so. I see a plate with a link to gun.eco website.

<img width="1051" alt="Screen Shot 2020-02-17 at 22 12 14" src="https://user-images.githubusercontent.com/609373/74680758-aadfd800-51d2-11ea-8f5d-aa8f4488cf52.png">

Also I don't think people who got on the website should go to github wiki, and I couldn't even imagine how they should figure this out and why they should, if they already visited a website. And the rhetorical question is it so important to have some fancy effect instead of being user-friendly and accessible.

**Comment by Dletta** [comment]
I agree with you that the effects are a bit much. I also know Mark is a one man show atm and is working hard on production readiness.

You can ignore the warning and search directly for the documentation you are looking for. The website was designed and built to pull from the wiki, so the content is the same.

Not sure exactly where the source of the website is, but if you find it a PR might get the switch implemented faster. I have a feeling @amark  will be busy with scaling production systems for another month or so

**Comment by rumkin** [comment]
Well I found where it is defined: https://github.com/amark/gun/blob/master/examples/style.css#L152
But the website's style source [css file](https://gun.eco/docs/72fc3d4628ee09039c8c64d588033ae4.css?bst=deb12ae92587e7415526c6f5b207e2dbc13588b3) differs and I can't find where does it get from. Here is the head of the the content:
```css
/* ----------- ADDITIONS BY MARK ------------------ */

@import url(https://fonts.googleapis.com/css?family=Oxygen);

html, body {
  color: white;
  font-size: 18pt;
  font-family: 'Oxygen', 'Trebuchet MS', arial;
  background: #4D79D8;
  -webkit-animation: hue 900s infinite;
  animation: hue 900s infinite;
}

.uk-h1, .uk-h2, .uk-h3, .uk-h4, .uk-h5, .uk-h6, h1, h2, h3, h4, h5, h6 {
  font-family: 'Oxygen', 'Trebuchet MS', arial;
}
```
I think it's really the think @amark could fix himself only or at least to tell what to do with this.
